### ISSUE TITLE
Add in new survey "PGP Basic Phenotypes Survey 2015"

### ISSUE THREAD

**Issue by abeconnelly** [PGPHarvard/pgp-surveys#1]
There's a new "PGP Basic Phenotypes Survey 2015" available through the web site.  It would nice to add it to this list.

It might also be good to know how to create and add surveys to this list.  Something like a basic tutorial on how to get the surveys, what format the surveys are expected to be in and a guideline for contribution (maybe this should go in a separate issue).

**Comment by nouyang** [comment]
Ah, I totally forgot. Yea, I can write up a quick tutorial in the readme sometime over the next week or two. The whole process probably takes less than 5 steps.

**Comment by nouyang-curoverse** [comment]
Ah, I totally forgot. Yea, I can write up a quick tutorial in the readme sometime over the next week or two. The whole process probably takes less than 5 steps.

**Comment by nouyang-curoverse** [comment]
Fixed and closed.
